### ISSUE TITLE
 Book Search Returns Incorrect Results

### ISSUE THREAD

**Issue by AYESH-pixel** [rk027738/LIS320#1]
The search function is returning inaccurate or incomplete results when searching for books. It appears the query is not properly filtering results by title or author.
Steps to Reproduce:
Go to the search bar.
Search for any book.
Inaccurate results are returned.
Expected vs Actual Behavior:
Expected: Search returns books by title, author, and keywords.
Actual: The search results are random and incorrect

**Comment by leylaisa** [comment]
Fixed the code accordingly and reached the expected results during manual testing.
<img width="602" alt="Screenshot 2024-12-23 at 1 18 09 AM" src="https://github.com/user-attachments/assets/c1ba5bed-9754-41e2-8b36-b151cc69333b" />
<img width="597" alt="Screenshot 2024-12-23 at 1 18 13 AM" src="https://github.com/user-attachments/assets/4d2c76fe-f278-4e02-a532-ef00a2e13c7c" />
